ci:
  skip: [pixi-install-locked]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        args: [--unsafe]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        types_or: [python, pyi]
        args: [--fix]
      - id: ruff-format
        types_or: [python, pyi]

  - repo: https://github.com/pecigonzalo/pre-commit-shfmt
    rev: v2.2.0
    hooks:
      - id: shell-fmt-go
        args:
          - --write
          - --simplify
          - --indent
          - "2"

  - repo: local
    hooks:
      - id: pyright
        name: pyright type checker
        entry: >
          bash -c 'cd $(git rev-parse --show-toplevel) &&
          pixi run pyright src/condorgmm/condor tests/condor'
        language: system
        types: [python]
        pass_filenames: false
        files: ^(src/condorgmm/condor|tests/condor)/.*$
      - id: pixi-install-locked
        name: pixi install
        entry: >
          bash -c 'cd $(git rev-parse --show-toplevel) &&
          pixi install'
        language: system
        files: ^pyproject\.toml$
        types: [text]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        files: \.yaml$
        additional_dependencies: ["prettier@3.0.0"]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        name: yamllint
        args: ["--format", "github"]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        name: Strip Notebook Outputs
        files: \.ipynb$
