name: YAML format

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ibiqlik/action-yamllint@v3
